# Generated by Django 4.1.3 on 2022-12-29 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0004_category_article_short_desc_article_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='short_desc',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
    ]
